### ISSUE TITLE
Map - Add in new buildings + fix bugs

### ISSUE THREAD

**Issue by rainerdeal** [WVU-Mobile/WVU-Mobile-iOS9#2]
Map needs to have the new buildings added and a few bugs fixed according to @katelandmesser.

**Comment by rainerdeal** [comment]
Oakland Hall, University Park, and Connector Building - don't know if there are more buildings than this...

**Comment by kaitlynlandmesser** [comment]
Added University Park and Evandale Crossing (Connector). Oakland hall appears to be part of University park and is not on the JSON feed so we won't add it at this time.

**Comment by kaitlynlandmesser** [comment]
Didn't we fix this?
